version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker_volumes/mongo:/data/db

  typesense:
    image: typesense/typesense:0.20.0
    restart: always
    ports:
      - 8108:8108
    environment:
      TYPESENSE_API_KEY: "fortnite"
      TYPESENSE_DATA_DIR: /data
    volumes:
      - ./docker_volumes/typesense:/data

  back_end:
    image: backend
    build: ./back-end
    depends_on:
      - mongo
      - typesense
    restart: always
    environment:
      TS_API_KEY: ${TS_API_KEY}
      TYPESENSE_HOST: ${TYPESENSE_HOST}
      APP_PORT: ${APP_PORT}
      MDBUSER: ${MDBUSER}
      MDBHOST: ${MDBHOST}
      MDBPASSWORD: ${MDBPASSWORD}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start
    volumes:
      - ./docker_volumes/backend:/data

  front-end:
    image: frontend
    build: ./front-end
    depends_on:
      - mongo
      - typesense
    restart: always
    environment:
      BACK_HOST: localhost
      APP_PORT: ${APP_PORT}
    ports:
      - 3000:3000
    command: npm run start
    volumes:
      - ./docker_volumes/backend:/data

